<div id="page-wrapper">
    <div class="header">
        <h1 class="page-header">
            Charts <small>Show up your stats</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li><a href="#">Charts</a></li>
            <li class="active">Data</li>
        </ol>

    </div>
    <div id="page-inner">

        <div class="row">
            <div class="col-sm-6 col-xs-12">
                <div class="panel panel-default chartJs">
                    <div class="panel-heading">
                        <div class="card-title">
                            <div class="title">Line Chart</div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <canvas id="line-chart" class="chart"></canvas>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-xs-12">
                <div class="panel panel-default chartJs">
                    <div class="panel-heading">
                        <div class="card-title">
                            <div class="title">Bar Chart</div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <canvas id="bar-chart" class="chart"></canvas>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-xs-12">
                <div class="panel panel-default chartJs">
                    <div class="panel-heading">
                        <div class="card-title">
                            <div class="title">Radar Chart</div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <canvas id="radar-chart" class="chart"></canvas>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-xs-12">
                <div class="panel panel-default chartJs">
                    <div class="panel-heading">
                        <div class="card-title">
                            <div class="title">Polar Area Chart</div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <canvas id="polar-area-chart" class="chart"></canvas>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-xs-12">
                <div class="panel panel-default chartJs">
                    <div class="panel-heading">
                        <div class="card-title">
                            <div class="title">Pie & Doughnut Chart</div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <canvas id="pie-chart" class="chart"></canvas>
                    </div>
                </div>
            </div>

            <div class="col-sm-6 col-xs-12">
                <div class="panel panel-default chartJs">
                    <div class="panel-heading">
                        <div class="card-title">
                            <div class="title">Line Chart</div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <canvas id="jumbotron-line-chart" class="chart no-padding"></canvas>
                    </div>
                </div>
            </div>
        </div>


        <footer><p>Copyright &copy; 2016.Company name All rights reserved.<a target="_blank" href="http://www.cssmoban.com/">&#x7F51;&#x9875;&#x6A21;&#x677F;</a></p></footer>
    </div>
    <!-- /. PAGE INNER  -->
</div>
<!-- /. PAGE WRAPPER  -->