<div id="page-wrapper">
    <div class="header">
        <h1 class="page-header">
            Empty Page <small>Create new page.</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li><a href="#">Empty</a></li>
            <li class="active">Data</li>
        </ol>

    </div>
    <div id="page-inner">
        <footer><p>Copyright &copy; 2016.Company name All rights reserved.<a target="_blank" href="http://www.cssmoban.com/">&#x7F51;&#x9875;&#x6A21;&#x677F;</a></p></footer>
    </div>
    <!-- /. PAGE INNER  -->
</div>
