</div>
</div>

<div id="footer">
    <hr/>
    <footer class="text-center">
        <p>&copy; 安好.inc <?=date('Y',time())?></p>
    </footer>
</div>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/jquery.ui.core.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/jquery.ui.widget.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/jquery.ui.mouse.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/jquery.ui.sortable.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/bootstrap.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/xadmin.main.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/xadmin.responsive.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/jquery.ui.effect.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/xadmin.plugin.themes.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/xadmin.page.dashboard.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/xadmin.plugin.portal.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/jquery.flot.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/jquery.flot.pie.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/jquery.flot.time.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/jquery.flot.resize.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/xadmin.plugin.charts.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/select2.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/xadmin.widget.select.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/xadmin.plugin.quick-form.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/bootstrap-timepicker.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/xadmin.page.form.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/xadmin.plugin.formset.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/xadmin.widget.select-transfer.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/xadmin.widget.datetime.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/xadmin.plugin.actions.js"></script>


</body>
</html>
<? //unset($data);
DEBUG == 1 && Yaf_Loader::import(PATH_APP . 'views/footer_debug.phtml') ?>
