<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="/static/vendors/kindeditor/themes/default/default.css" rel="stylesheet">
    <link href="<?php echo STATIC_FILE_BASE_URL;?>static/vendors/jquery/jquery-ui.css" rel="stylesheet">
    <link href="<?php echo STATIC_FILE_BASE_URL;?>static/vendors/jquery/jquery-ui-timepicker-addon.css"  rel="stylesheet">
    <link href="<?php echo STATIC_FILE_BASE_URL;?>static/vendors/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo STATIC_FILE_BASE_URL;?>static/vendors/bootstrap/bootstrap-select.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/main.css">
    <link rel="stylesheet" href="/static/css/gm.css">
    <link rel="stylesheet" href="/static/css/icon.css">
    <script src="<?php echo STATIC_FILE_BASE_URL;?>static/vendors/jquery/jquery-1.11.2.min.js"></script>
    <script src="<?php echo STATIC_FILE_BASE_URL;?>static/vendors/jquery/jquery-ui.js"></script>
    <script src="<?php echo STATIC_FILE_BASE_URL;?>static/vendors/jquery/jquery-ui-timepicker-addon.js"></script>
    <script src="<?php echo STATIC_FILE_BASE_URL;?>static/vendors/jquery/jquery-ui-timepicker-zh-CN.js"></script>
    <script src="/static/vendors/jquery/jquery.fileupload.js"></script>
    <script src="<?php echo STATIC_FILE_BASE_URL;?>static/vendors/bootstrap/js/bootstrap.min.js"></script>
    <script src="<?php echo STATIC_FILE_BASE_URL;?>static/vendors/bootstrap/bootstrap-select.js"></script>
    <script src="<?php echo STATIC_FILE_BASE_URL;?>static/vendors/kindeditor/kindeditor-min.js"></script>
    <script src="<?php echo STATIC_FILE_BASE_URL;?>static/vendors/charts/highcharts.js"></script>
    <script src="/static/js/main.js"></script>
    <script src="/static/js/mycommon/addextendsparams.js"></script>
    <script src="/static/js/mycommon/publicone.js"></script>
    <script src="<?php echo STATIC_FILE_BASE_URL;?>static/js/echarts-all.js"></script>
    <title><?php
    if(isset($data['title'])){
        echo $data['title'];
    }
    ?></title>
</head>