<!-- /. PAGE WRAPPER  -->
</div>
<!-- /. WRAPPER  -->
<!-- JS Scripts-->
<!-- jQuery Js -->
<script src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/dataTables/dataTables.bootstrap.js"></script>
<script src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/dataTables/jquery.dataTables.js"></script>
<script src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/Lightweight-Chart/chart.js"></script>
<script src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/Lightweight-Chart/jquery.chart.js"></script>
<script src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/chart-data.js"></script>
<script src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/custom.js"></script>
<script src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/easypiechart.js"></script>
<script src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/easypiechart-data.js"></script>
<script src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/select2.full.min.js"></script>




<script src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/jquery-1.10.2.js"></script>
<!-- Bootstrap Js -->
<script src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/bootstrap.min.js"></script>
<!-- Metis Menu Js -->
<script src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/jquery.metisMenu.js"></script>
<!-- Chart Js -->
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/Chart.min.js"></script>
<script type="text/javascript" src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/chartjs.js"></script>
<!-- Morris Chart Js -->
<script src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/morris/raphael-2.1.0.min.js"></script>
<script src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/morris/morris.js"></script>
<!-- Custom Js -->
<script src="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/custom-scripts.js"></script>

</body>
</html>