<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta content="" name="description" />
    <meta content="webthemez" name="author" />
    <title><?php echo $_data['__title__'];?></title>
    <!-- Bootstrap Styles-->
    <link href="<?php echo STATIC_FILE_BASE_URL;?>static/admin/css/bootstrap.css" rel="stylesheet" />
    <!-- FontAwesome Styles-->
    <link href="<?php echo STATIC_FILE_BASE_URL;?>static/admin/css/font-awesome.css" rel="stylesheet" />
    <!-- Morris Chart Styles-->
    <link href="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/morris/morris-0.4.3.min.css" rel="stylesheet" />
    <!-- Custom Styles-->
    <link href="<?php echo STATIC_FILE_BASE_URL;?>static/admin/css/custom-styles.css" rel="stylesheet" />
    <link href="<?php echo STATIC_FILE_BASE_URL;?>static/admin/css/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="<?php echo STATIC_FILE_BASE_URL;?>static/admin/css/checkbox3.min.css" rel="stylesheet" />
    <link href="<?php echo STATIC_FILE_BASE_URL;?>static/admin/css/select2.min.css" rel="stylesheet" />
    <!-- Google Fonts-->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <link href="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/dataTables/dataTables.bootstrap.css" rel="stylesheet" />
    <link href="<?php echo STATIC_FILE_BASE_URL;?>static/admin/js/Lightweight-Chart/cssCharts.css" rel="stylesheet" />
</head>
<body>


