<nav class="navbar-default navbar-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="main-menu">

            <li>
                <a href="index"><i class="fa fa-dashboard"></i> Dashboard</a>
            </li>
            <li>
                <a href="ui-elements"><i class="fa fa-desktop"></i> UI Elements</a>
            </li>

            <li>
                <a href="#" class="active-menu"><i class="fa fa-sitemap"></i> Charts<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="chart">Charts JS</a>
                    </li>
                    <li>
                        <a href="morris-chart">Morris Chart</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="tab-panel"><i class="fa fa-qrcode"></i> Tabs & Panels</a>
            </li>

            <li>
                <a href="table"><i class="fa fa-table"></i> Responsive Tables</a>
            </li>
            <li>
                <a href="form"><i class="fa fa-edit"></i> Forms </a>
            </li>


            <li>
                <a href="#"><i class="fa fa-sitemap"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="#">Second Level Link</a>
                    </li>
                    <li>
                        <a href="#">Second Level Link</a>
                    </li>
                    <li>
                        <a href="#">Second Level Link<span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level">
                            <li>
                                <a href="#">Third Level Link</a>
                            </li>
                            <li>
                                <a href="#">Third Level Link</a>
                            </li>
                            <li>
                                <a href="#">Third Level Link</a>
                            </li>

                        </ul>

                    </li>
                </ul>
            </li>
            <li>
                <a href="empty"><i class="fa fa-fw fa-file"></i> Empty Page</a>
            </li>
        </ul>

    </div>
</nav>