<nav class="navbar-default navbar-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="main-menu">
            <?php foreach($_data['__nav_cat__']['_top_'] as $key=>$value){?>
                <li>
                    <a href="<?php echo  $value['url'];?>" class="<?php if(1 == $value['is_checked']){ echo 'active-menu';} else{ echo 'ui-elements';}?>"><i class="fa fa-sitemap"></i><?php echo  $value['title'];?><span class="fa arrow"></span></a>
                    <?php if($value['list']){?>
                    <ul class="nav nav-second-level">
                        <?php foreach($value['list'] as $_key=>$_value){?>
                        <li>
                            <a href="<?php echo $_value['url'];?>"><?php echo $_value['title'];?></a>
                        </li>
                        <?php }?>
                    </ul>
                    <?php }?>
                </li>
            <?php }?>
        </ul>

    </div>
</nav>